### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Lonewolf30** [chibill/AutoCrafters#11]
MC Version : 1.13

Plugin Version : 1.6.0

The problem? : When auto crafting dried kelp blocks

What you expect to happen : consume items

What actually happened : the items in the input chest requires no input items

Steps to reproduce.
normal setup but with dried kelp blocks and remove all dried kelp from input chest

**Comment by wgaylord** [comment]
I haven’t touched 1.13 yet and the mod does support it yet technically. Give me time to look into what I need to fix in general with this update.

**Comment by Maleachi** [comment]
Didn´t open a new issue as this is the same bug on an later version...

MC Version :
1.13.1 (CraftBukkit version git-Bukkit-db10914 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT))

Plugin Version :
AutoCrafters 1.7.0-Beta

The problem? : 
Kelb_blocks can be crafted with no cost.

What you expect to happen :
Dried kelp from input chest to be used up.

What actually happened :
Dried kelp stays untouched in input chest, I can also create Kelpblocks without any dried kelp in the Input chest. 

Steps to reproduce.
Create a craftbukkit server and install plugin. use autocrafter as known...

**Comment by wgaylord** [comment]
Considering I tested this dirrectly before publishing I have a question. What other plugins are on your server? And I tested on 1.13.1

**Comment by wgaylord** [comment]
This seems odd as I specifically tested it using dried kelp. I will investigate. Is the only plugin in the server AutoCrafters?

**Comment by Maleachi** [comment]
No, I have also Dynmap-3.0-beta-1 installed.

**Comment by Maleachi** [comment]
[Testworld.zip](https://github.com/wgaylord/AutoCrafters/files/2502448/Testworld.zip)
I have created a new World with only Autocrafters, to test if there is any odd going on and it also has the bug...
I have uploaded the world, including server.properties bukkit.yml. 
So only craftbukkit is missing. maybe it´s my craftbukkit build that has odds or my configs are to blame.

**Comment by wgaylord** [comment]
Maleachi please update to the 1.7.0 Beta from your world download I can see you have 1.6.0 which does not have 1.13 support.
