### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by Hendrikto** [chibill/AutoCrafters#12]
# Template

MC Version: `1.13.2`

Plugin Version: `1.7.0-Beta`

The problem: By toggling the redstone signal really fast, for example by manually placing and removing redstone torches, it is possible to duplicate items.

What you expect to happen: You should only be able to craft 7 Gold Ingots from 64 Gold Nuggets, as each ingot requires 9 nuggets.

What actually happened: I got 16 Gold Ingots from 64 Gold Nuggets

Steps to reproduce: Place a chest with 64 Gold Nuggets in it. Place another chest 1 block away from it. Place an AutoCrafter between the chests, facing into the empty chest. Put a Gold Ingot into the AutoCrafter. (until now, this is the normal setup)

At this point comes the bug: Take a redstone torch, and place it next to the AutoCrafter to activate it. Immediate remove the torch, and place it again. Repeat this until the input chest is empty. You should have 16 Gold Ingots, if you did it fast enough.

# Additional Information

This is similar to https://github.com/wgaylord/AutoCrafters/issues/11, but I opened a new issue, because the behavior is different. The items are actually consumed, just not enough of them. Also this does not happen when using a normal redstone clock to trigger the AutoCrafter, just when doing it really fast.

**Comment by wgaylord** [comment]
Hm interesting. I might try and fix this but also if you wish to quickly run an autocrafter use the efficiency enchantment.

**Comment by Hendrikto** [comment]
The main reason this is a problem is that we want to use it on our multiplayer server where you cannot rely on people not abusing this on purpose. Thanks for looking into this.

**Comment by wgaylord** [comment]
I might know the problem and it has to do with how bukkit does events. I believe before it is done processing one redstone torch placement it starts processing another.

So the chests don't update between them.

I will work on an update to fix this.

**Comment by wgaylord** [comment]
It seems to be specific to the gold nugget not as I suspected.  This may take some time.

**Comment by Hendrikto** [comment]
I just tried to reproduce this using Iron Nuggets. I was not able to get this behavior. It seems that you are correct in that the issue is exclusive to Gold Nuggets. Very strange.

**Comment by wgaylord** [comment]
> I just tried to reproduce this using Iron Nuggets. I was not able to get this behavior. It seems that you are correct in that the issue is exclusive to Gold Nuggets. Very strange.

Yea. So for now you could blacklist the crafting of gold ingots in the config.  Untill I figure out the problem.

**Comment by ghost** [comment]
It doesn't only not work on gold nuggets, iron ones are also affected
[video.zip](https://github.com/wgaylord/AutoCrafters/files/3537819/video.zip)

**Comment by wgaylord** [comment]
Hm. Very odd. I guess I will have to figure out what the heck is still causing this.
Btw what version are you on?

**Comment by ghost** [comment]
1.14.4 It looks like sometimes nuggets are treat like blocks by the autocrafter, maybe it's because ingots have two recipes?
