### ISSUE TITLE
Crafting Ingredients arent used upon crafting!

### ISSUE THREAD

**Issue by xCrimsonAxe** [chibill/AutoCrafters#13]
MC Version : 1.14.4

Plugin Version : 1.7.1 / 1.7.0 - other versions not testest

The problem? : Crafting Firework rockets doesn't work right.

What you expect to happen : Paper and Gunpowder should have disappeared.

What actually happened : The Crafting Ingredients aren't removed from the input chest.

Steps to reproduce : Simply hook up the System and let it run.

**Comment by wgaylord** [comment]
Rockets are a special case I have never dealt with. (Also sort of forgot about) right now crafters don’t take into consideration the NBT data on the item being crafted for example. Fireworks ,  colored leather armor, and maybe something else I have not though of. I will start working on this right away. Annoying college just started back up so there may be some delay.

**Comment by wgaylord** [comment]
Current version does not supporting rocket so marking this as fixed. (It literally will not craft so this bug will no longer happen.)
