### ISSUE TITLE
Wont craft items

### ISSUE THREAD

**Issue by sportsziggy** [chibill/AutoCrafters#14]
MC Version : 1.14.4

Plugin Version : 1.7.1

The problem? : Won't craft any blocks

What you expect to happen : Craft blocks

What actually happened : No blocks are crafted

Steps to reproduce : Start a 1.14.4 spigot/craftbukkit multiplayer server and try and run the autocrafter. Alternatively, join my server.

**Comment by wgaylord** [comment]
Interesting. Any other information on what your running on your server? Could be another plugin is messing stuff up. As I developed the latest update using 1.14.4 and it worked and this is the first problem like this reported.

**Comment by sportsziggy** [comment]
The latest spigot w/ ChopTree2, WorldEdit, OpenInv, GetSpawnersTwo, and ShulkerPacks.

**Comment by wgaylord** [comment]
Question are you getting any errors in your logs? Also I could hope on your server and try testing it out.

**Comment by sportsziggy** [comment]
![image](https://user-images.githubusercontent.com/1366131/63730230-5fa6c700-c838-11e9-9dad-025b517aea81.png)
And no error logs.
If you want the IP address to check it out lmk and i'll DM you it.

**Comment by wgaylord** [comment]
Hm odd. You are providing a Redstone signal to tell it to craft right?

**Comment by sportsziggy** [comment]
Yup, you can see the particle effects
![image](https://user-images.githubusercontent.com/1366131/63730391-1d31ba00-c839-11e9-8d03-e8b907a2be10.png)

**Comment by wgaylord** [comment]
Could you send me your server ip. Also be aware double chest functionality is sort of broken. It only affects the chest nearest.

**Comment by sportsziggy** [comment]
> 
> Could you send me your server ip. Also be aware double chest functionality is sort of broken. It only affects the chest nearest.
> […](#)
> On Aug 26, 2019, at 6:38 PM, sportsziggy ***@***.***> wrote: Yup, you can see the particle effects — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Yeah, I tried single chests as well.
100.14.61.7
What is your IGN? I'm going to assume its your github name and whitelist that for the time being.

**Comment by wgaylord** [comment]
It’s chibill

**Comment by sportsziggy** [comment]
> 
> It’s chibill
> […](#)
> On Aug 26, 2019, at 8:50 PM, sportsziggy ***@***.***> wrote: Could you send me your server ip. Also be aware double chest functionality is sort of broken. It only affects the chest nearest. … On Aug 26, 2019, at 6:38 PM, sportsziggy @.***> wrote: Yup, you can see the particle effects — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. Yeah, I tried single chests as well. 100.14.61.7 What is your IGN? I'm going to assume its your github name and whitelist that for the time being. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

added.

**Comment by wgaylord** [comment]
Seems I am not whitelisted still.

**Comment by sportsziggy** [comment]
> 
> 
> Seems I am not whitelisted still.

chibill is correct?

**Comment by wgaylord** [comment]
yes

**Comment by sportsziggy** [comment]
looks like there were multiple chibill 's and i had the wrong id
should be good now
