### ISSUE TITLE
Nonstop Dispenser Sound

### ISSUE THREAD

**Issue by Sander0542** [chibill/AutoCrafters#15]
MC Version :

1.14.4

Plugin Version :

1.7.1

The problem? : 

Dispenser sounds

What you expect to happen :

Only hear a sound when the dispenser actually crafts an item.

What actually happened :

A dispenser sound every time the AutoCrafter triggers.

Steps to reproduce.

1. Build an AutoCrafter with Infinity.
2. Enable the AutoCrafter with Redstone

**Comment by wgaylord** [comment]
This isn’t a bug. Every time it attempts to craft an item you hear it. As I use the dispense event to run the crafting code.
