### ISSUE TITLE
issues with honey blocks

### ISSUE THREAD

**Issue by hurricaneJoef** [chibill/AutoCrafters#18]
MC Version :1.16.1

Plugin Version :2.0.1

The problem? : when crafting honey blocks the glass bottles disappear 

What you expect to happen : the empty bottles should be either left in the dispenser or left in the output chest

What actually happened :i dont get glass bottles

Steps to reproduce. 

                                     [button]

[output chest] [crafter with honey block in]   [chest with honey bottles]
![2020-08-12_20 12 40](https://user-images.githubusercontent.com/33767776/90080293-38126e00-dcd8-11ea-858b-d5b796ee27b1.png)

**Comment by wgaylord** [comment]
I knew exactly how to fix this. For crafting recipes that leave items in the grid i have to special case it.  For example crafting cake. I will put out a fix as quickly as i can. (Maybe even today depending in how busy i am between now (7:24 pm CST) and when i go to bed (normally after midnight).

**Comment by wgaylord** [comment]
Fixed in latest update. :)
