### ISSUE TITLE
server restart unloads existing autocrafters

### ISSUE THREAD

**Issue by Sidious82** [chibill/AutoCrafters#2]
The problem? : 
every time the server stops my autocrafters stop working
What you expect to happen:
when i return to my autocrafter it should be working properly 100% of the time
What actually happened:
the autocrafter stops working, must be broken, re-crafted and replaced
Steps to reproduce.
stop the server, start the server, try to use your autocrafter

**Comment by wgaylord** [comment]
Can you give more information about what type of autocrafter your using? (Eff or infinity). Also are you sure it is powered and in a loaded Chunk?

**Comment by wgaylord** [comment]
Okay I have found the problem. The onPlace event has two many blocks it keeps track of. :|

**Comment by wgaylord** [comment]
Okay while looking for this bug. (Which was just forgetting to have <= instead of just <.)
I found another bug that has existed from the start.

I will be releasing a update after I make sure there are no more bugs I can find.

**Comment by Sidious82** [comment]
the effeciency works as you say it should

the infinity doesnt seem to work at all

the autocrafters are indeed powered

it doesnt seem to matter what chunks they are placed in, once the server stops they must be re-placed.


another issue:  you can only enchant dispensers while in creative gamemode therefore my regular players cannot craft this feature.

________________________________

**Comment by wgaylord** [comment]
I just fixed the infinity one in 1.5. Working on the enchant one.

**Comment by Sidious82** [comment]
you have no idea how long i searched for this plugin.  thank you so much for your hard work!  the players i have shown love it too.  (p.s. my autocrafters survived a server restart!)  [👍]

________________________________

**Comment by wgaylord** [comment]
Also you can now sort of enchant them in the anvil in survival. Place them in the click the last lost. It will give it to you.
