### ISSUE TITLE
1 Iron Nugget turns into 9 Iron Ingots

### ISSUE THREAD

**Issue by bigbarbecuetime** [chibill/AutoCrafters#20]
MC Version : 1.16.3 (Paper ver 240)

Plugin Version : 2.0.0 - 2.0.2

The problem? : When using the autocrafter to create an iron ingot, 1 iron nugget creates 9 ingots. (This specifically only happens with 1 iron nugget, any other value works as intended)

What you expect to happen : The iron ingot should not craft, because there is only 1 iron nugget

What actually happened : 1 nugget is turned into 9 ingots

Steps to reproduce. Using version 1.16.3, place 1 iron nugget into the input, and set the autocrafter to create 1 iron ingot. Then activate the autocrafter, 9 iron ingots should be in the output.

**Comment by wgaylord** [comment]
What other plugins are you using?

**Comment by bigbarbecuetime** [comment]
No other plugins

**Comment by wgaylord** [comment]
I have never seen this happen in all my attempts to reproduce it and also its the only time this issue accord if it even did. Closing this.
