### ISSUE TITLE
How do i use the autocrafter to craft iron block?

### ISSUE THREAD

**Issue by Yap0n** [chibill/AutoCrafters#21]
MC Version :1.17

Plugin Version :Lastest (2.0.2)

The problem? : I don't understand how to craft stuff i want to craft iron block from my iron farm

What you expect to happen :

What actually happened :

Steps to reproduce.

**Comment by wgaylord** [comment]
Place an iron block inside the crafter. It looks up the recipe for it then takes the required items from the input chest and places the output in the output chest.

**Comment by wgaylord** [comment]
Also I am currently updating the plugin for 1.17 and doing alot of work on it, just takes time due to my work schedule.

**Comment by Yap0n** [comment]
Do i need to make a redstone to power it after put in infinity

**Comment by Yap0n** [comment]
and may i have a picture of the perfect setup for it

**Comment by Yap0n** [comment]
https://cdn.discordapp.com/attachments/859012376418451456/859701050961428480/2021-06-30_14.43.44.png

This is what i understand and do

**Comment by Yap0n** [comment]
but i understand that the output chest is the side that the dropper facing but when it drop item it doesn't go in the chest it just go off

**Comment by wgaylord** [comment]
There must be a chest of both sides of the dropper ,(face side and the side opposite it.) You put the input in the chest opposite the face  put one of the items you want to craft into the dropper then power the dropper and it will craft.
