### ISSUE TITLE
AutoCrafters dont drop properly

### ISSUE THREAD

**Issue by pokemonrocks9** [chibill/AutoCrafters#22]
MC Version :1.17

Plugin Version :2.0.2

The problem? : When you break and replace an autocrafter it no longer works

What you expect to happen :Breaking and replacing an autocrafter to work still

What actually happened : the autocrafter became a dispenser

Steps to reproduce.
Place autocrafter, break autocrafter, place autocrafter

**Comment by wgaylord** [comment]
As stated in the plugins thread on Spigots website i am working on a 1.17 update.

**Comment by wgaylord** [comment]
Should be fixed in latest release
