### ISSUE TITLE
when you break the autocrafters they lose thier lore and work like a normal dispenser

### ISSUE THREAD

**Issue by yiddir23** [chibill/AutoCrafters#23]
MC Version : 1.19

Plugin Version : 2.0.2

The problem? : Crafters lose their lore whenever they are broken

What you expect to happen : they don't lose thier lore and you should be able to use them again

What actually happened : you can't use them as a crafter it's just a normal dispenser

Steps to reproduce.

**Comment by wgaylord** [comment]
I being out of town this weekend but on Monday I will try and get an update out for 1.19. I haven't touched the plugin at all in a while.

**Comment by wgaylord** [comment]
Also btw do you have any thing in the server logs? (Also if you could post the data.json from the autocrafters folder in the plugins folder that would be great.

**Comment by wgaylord** [comment]
Fixed in latest release
