### ISSUE TITLE
Please add Support for MC 1.21.1

### ISSUE THREAD

**Issue by Leahcimkrob** [chibill/AutoCrafters#24]
MC Version : 1.21.1

Plugin Version : 2.1.1

The problem? : Plugin will not work

**Comment by wgaylord** [comment]
I see no point in updating the plugin past 1.20 due to aurocrafters now existing in the game itself.  

Unless there is a good reason for it.

**Comment by Leahcimkrob** [comment]
It's true that there are MC crafters, but they're really laggy. You always need an active redstone clock for them to really work automatically, which can lead to lag on large servers. If redstone is banned on a server, you can't use the MC crafters, so I'd like to ask you again: can you update your plugin to MC 1.21.1?

**Comment by wgaylord** [comment]
I am updating it now. Not sure what could have broken it, but time to fine out.

**Comment by Leahcimkrob** [comment]
Thank you

**Comment by wgaylord** [comment]
Had been updated, turns out just to be Enum name changes that broke it.
