### ISSUE TITLE
ingredients in "input" chest are used regardless of wether "output" chest is full or not.

### ISSUE THREAD

**Issue by Sidious82** [chibill/AutoCrafters#4]
The problem? : 
autocrafter can potentially waste valueable recipe ingredients by crafting into a full chest

What you expect to happen: 
some sort of "safety" stop where the autocrafter simply stops working if the output chest is full

What actually happened:
ingredients in "input" chest are used regardless of current state of "output" chest.

Steps to reproduce.
build autocrafter, place recipe and work as normally intended.  once output chest is full, continue to send a redstone signal to the autcrafter:  it will pull ingredients but produce no product.

**thank you for all your hard work.  this plugin is great!  my whole community loves it.

**Comment by wgaylord** [comment]
I will try to reproduce this. But this is one of the things I tested for.

**Comment by Sidious82** [comment]
if i was not clear enough i am happy to communicate further.  i can reproduce this 100% of the time i try

**Comment by wgaylord** [comment]
I can't reproduce this at all. What version of Autocrafters are you using?
Also this basic check has been in the code from 1.0.0. And I just double checked it now.

Steps that you did to get it to happen?
