### ISSUE TITLE
[Server thread/WARN]: [AutoCrafters] Task #785 for AutoCrafters v1.5.2 generated an exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by Sidious82** [chibill/AutoCrafters#5]
The problem? : updated to latest spigot build and plugin is throwing infinit console errors/spam

What you expect to happen: no console spam/errors

What actually happened: tons of console spam/errors

Steps to reproduce. not sure on this one, all i did was update to the latest buildtools and started the server.

see discord for a copy of server startup/shutdown + errors included

**Comment by Sidious82** [comment]
resolved issue by regenerating autocrafters file.  my theory is a player created some sort of broken setup.

**Comment by wgaylord** [comment]
Still this is something I need to investigate.
