### ISSUE TITLE
AutoCrafters 1.12.1 Issue.

### ISSUE THREAD

**Issue by sannielollie** [chibill/AutoCrafters#6]
The problem? : AutoCrafters not working any more on 1.12.1

What you expect to happen: It would be nice if the plugin works on 1.12.1

What actually happened: AutoCrafters worked flawnless on 1.12 Spigot. Since i have updated to Spigot 1.12.1 its no longer working. Plugin is still loading like it should, no errors found in the logfile regarding the plugin itself. 

[03:03:06] [Server thread/INFO]: [AutoCrafters] Loading AutoCrafters v1.5.4 
[03:03:18] [Server thread/INFO]: [AutoCrafters] Enabling AutoCrafters v1.5.4 
[03:03:18] [Server thread/INFO]: [AutoCrafters] AutoCrafters are now enabled! 
[03:03:18] [Server thread/INFO]: [AutoCrafters] Config.yml found, loading! 

Complete startup log: https://pastebin.com/300H6xwk

Steps to reproduce : 
Use Spigot 1.12.1 together with AutoCrafters plugin. It works, u can rename a dispenser to AutoCrafter with anvil, place it, place 2 chests like explained in the tutorial. Put item to craft in AutoCrafter dispenser, put in materials in inputchest, give redstone signal to furnace (i use torch underneath it with a simple comparator clock) = no output in output-chest.

**Comment by wgaylord** [comment]
Quite odd. I will take a look in the morning. Tho from reading the bukkit change logs nothing has changed that I use between the two versions. Could possibly be another plugin messing it up

**Comment by wgaylord** [comment]
Fixed in 1.5.5
