### ISSUE TITLE
losing buckets

### ISSUE THREAD

**Issue by frankhta** [chibill/AutoCrafters#8]
MC Version :1.12

Plugin Version :1.6.0

The problem? : this isn't an issue it's just a suggestion but when you craft cakes you lose your buckets is there any way for you to fix it so that you don't lose all the buckets

What you expect to happen : I am expecting not to lose all my buckets

What actually happened :I'm actually losing my buckets when I craft cake

Steps to reproduce.I'm not sure what to put here

**Comment by wgaylord** [comment]
This will be fixed in the next release and steps to reproduce basically means what you did to get this to happen.

**Comment by wgaylord** [comment]
Fixed
