### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by crusher42** [chibill/AutoCrafters#9]
MC Version :1.12

Plugin Version :1.6.0

The problem? :  it's not an issue you but a suggestion 
                          can you make it that the import chest that's takes all items but one
                          can you make it that it can be toggleable in the config as well

What you expect to happen :

What actually happened :

Steps to reproduce.

**Comment by wgaylord** [comment]
I might be able to implement this.

**Comment by wgaylord** [comment]
Sorry I haven’t done anything with this. Been having a hard time with chests (double chest code is annoying because of the lack of a good api) and I haven’t looked at this.
